# Generated by Django 3.2 on 2022-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
