# Generated by Django 3.2 on 2022-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220610_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.AddField(
            model_name='label',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='projects.Project'),
        ),
    ]
