# Generated by Django 3.2 on 2022-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220610_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Project'),
        ),
    ]
