# Generated by Django 3.2 on 2022-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='label', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='project', to='projects.Label'),
        ),
    ]
