# Generated by Django 3.2 on 2022-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220610_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='likes',
        ),
        migrations.AlterField(
            model_name='project',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='user_ratings', to='projects.Rating'),
        ),
    ]
