# Generated by Django 3.2 on 2022-06-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220610_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ratings',
        ),
        migrations.AddField(
            model_name='project',
            name='ratings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='projects.rating'),
        ),
    ]
