# Generated by Django 3.2 on 2022-06-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220610_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ratings',
        ),
        migrations.AddField(
            model_name='project',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='user_ratings', to='projects.Rating'),
        ),
    ]
