# Generated by Django 3.2 on 2022-06-11 02:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
