# Generated by Django 3.2 on 2022-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='creativity',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
