# Generated by Django 3.2 on 2022-06-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creativity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.FloatField(default=0),
        ),
    ]
